# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

# np.zeros( (x,y) ): 建立全為 0的x*y全零矩陣
# np.empty(): 用法與np.zeros一樣，但唯一的差別是NumPy不會初始化陣列內元素的初始值，資料未指定，所以內容將會是不確定的。

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [23]:

a = np.random.rand(2, 3)
print(a)
print(a.round())
print(np.round(a))

[[0.00319795 0.41259992 0.98325778]
 [0.50932837 0.41082457 0.06073562]]
[[0. 0. 1.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [1. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [24]:
m = 20
n = 40

b = a * (n-m)
print(b)
print((b - b % 1)+m)



[[ 0.063959    8.25199834 19.66515569]
 [10.18656733  8.21649149  1.2147124 ]]
[[20. 28. 39.]
 [30. 28. 21.]]
