# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [10]:
# 記得先 Import 正確的套件
import numpy as np

a=np.arange(1,12)
print(a)
# print(a[(3 <= a) & (a < 7)] ) #確認有無找錯
a[(3 <= a) & (a < 7)] *= -1
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11]
[3 4 5 6]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [9]:
A = np.random.rand(3, 6)

print(A)
# print(A[A > 0.5]) # 先找出比 0.5 大的數
print(A[A > 0.5].size)

[[0.75210669 0.53971262 0.3662156  0.79958343 0.05629771 0.57630368]
 [0.98484285 0.25154178 0.96960599 0.99998232 0.34367074 0.86205558]
 [0.44598884 0.48693543 0.03369879 0.32921813 0.62763597 0.64119241]]
[0.75210669 0.53971262 0.79958343 0.57630368 0.98484285 0.96960599
 0.99998232 0.86205558 0.62763597 0.64119241]
10
