# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 100 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [3]:
import numpy as np

In [9]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [14]:
%timeit -n 10 a = 2

print (Z)

for i in Z:
    for j in i:
        for k in j:
            i = i + 1

37.1 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[5 9 5 ... 6 1 3]
  [6 3 1 ... 7 7 9]
  [3 7 9 ... 9 3 4]
  ...
  [7 0 7 ... 0 3 4]
  [0 9 8 ... 0 3 2]
  [7 3 2 ... 7 1 7]]

 [[6 3 8 ... 6 3 6]
  [2 8 4 ... 6 1 5]
  [4 3 3 ... 9 2 4]
  ...
  [5 2 5 ... 5 2 9]
  [2 5 6 ... 6 5 4]
  [6 6 9 ... 4 4 0]]

 [[9 9 2 ... 8 6 5]
  [3 3 7 ... 1 8 8]
  [3 8 7 ... 8 6 3]
  ...
  [6 9 9 ... 4 7 4]
  [3 2 0 ... 9 5 6]
  [4 0 0 ... 4 1 9]]

 ...

 [[2 2 5 ... 3 5 6]
  [8 3 7 ... 8 0 7]
  [9 2 3 ... 5 5 5]
  ...
  [6 6 4 ... 8 7 7]
  [5 7 7 ... 2 5 3]
  [6 2 0 ... 6 3 4]]

 [[3 5 1 ... 2 1 6]
  [1 9 1 ... 2 5 5]
  [4 3 4 ... 6 9 9]
  ...
  [0 8 4 ... 4 2 0]
  [6 7 1 ... 1 9 4]
  [3 7 7 ... 0 9 5]]

 [[8 9 3 ... 5 8 1]
  [9 3 5 ... 1 7 4]
  [2 2 9 ... 8 8 3]
  ...
  [9 5 5 ... 7 9 2]
  [3 4 7 ... 5 2 9]
  [3 9 5 ... 2 8 0]]]


In [15]:
%timeit -n 10 a = 2

for i in Z.flat:
    i = i+1

38.6 ns ± 9.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [13]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i = i+1

81.4 ns ± 8.33 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [4]:
A = np.random.randint(0,10,50)
print(A)
B = (np.bincount(A).argmax())
print(B)
print(np.where(A == B))# np.where()[0] 表示行索引，np.where()[1]表示列索引
print(np.where(A == B)[0]) #它大致說的是bin的數量比x中的最大值大1，每個bin給出了索引值在x中出現的次數，下面以例項說明


[5 9 4 3 3 2 9 3 8 3 5 0 5 8 7 6 1 7 5 5 3 9 9 4 2 3 4 8 5 2 3 1 3 1 0 0 5
 8 3 1 6 1 6 5 0 2 9 4 6 6]
3
(array([ 3,  4,  7,  9, 20, 25, 30, 32, 38], dtype=int64),)
[ 3  4  7  9 20 25 30 32 38]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [19]:
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

[9, 5, 6, 7, 6, 8]
[9, 5, 6, 7, 6, 8]
[[0, 4, 1, 1], [7, 7, 1, 5], [5, 4, 9, 1]]
[array([0, 4, 1, 1]), array([7, 7, 1, 5]), array([5, 4, 9, 1])]
[[[9, 5], [1, 4], [4, 8]], [[7, 9], [1, 2], [5, 1]]]
[array([[9, 5],
       [1, 4],
       [4, 8]]), array([[7, 9],
       [1, 2],
       [5, 1]])]


In [ ]:
### 進階題目

作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
print(array2)
print(np.dot(array1,array2))


[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


In [3]:
#2. 運用上列array計算特徵值、特徵向量?
eigvalue, eigvector = np.linalg.eig(array1)
print('\n','eigvalue = ',eigvalue)
print('\n','eigvector = \n',eigvector)



 eigvalue =  [13.  2.]

 eigvector = 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
#3. 運用上列array計算SVD?
print('\n','SVD = \n',np.linalg.svd(array1))


 SVD = 
 (array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]]), array([13.94721714,  1.86417116]), array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]]))
