# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [15]:
# a.sum()只適用於a為 Array
# np.sum(a)適用於a為Array或列表
# sum(a)適用於a為一維的列表或任何維度的Array，或當a為二維以上的Array時則會降維

import numpy as np 

# 使用 Array
a = np.array((1,3,4))
print(a.sum()) 
print(np.sum(a))
print(sum(a))

# 使用 Tuple
b = (1,2,4)
# print(b.sum())  'tuple' object has no attribute 'sum'
print(np.sum(b))
print(sum(b))

# 使用 List 
c = [1,2,3]
# print(c.sum())  'list' object has no attribute 'sum' 
print(np.sum(c))
print(sum(c))

# 使用 二維 Array
d = np.array([[4,3,4],[1,1,1]])
print(d.sum()) 
print(np.sum(d))
print(sum(d))


8
8
8
7
7
6
6
14
14
[5 4 5]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [32]:
# 記得先 Import 正確的套件

import matplotlib.pyplot as plt
A = np.random.random((5, 5))
B = A.copy()
B = (B-B.min())/(B.max()-B.min())
print(A,B,sep='\n')

#normalized_v = A/np.linalg.norm(A)
#print(normalized_v)

[[0.44868987 0.61581938 0.71741897 0.8002104  0.23602041]
 [0.9638536  0.44981255 0.87162682 0.35290166 0.18083407]
 [0.46080463 0.98926031 0.46174854 0.26884899 0.77404343]
 [0.09071324 0.1428292  0.31822261 0.04182994 0.97170749]
 [0.73867709 0.49370749 0.62707272 0.83910177 0.27573884]]
[[0.42943518 0.60583813 0.71307513 0.80046037 0.20496543]
 [0.97318356 0.43062015 0.87583944 0.32833202 0.14671699]
 [0.44222215 1.         0.44321843 0.23961555 0.77284148]
 [0.05159567 0.10660336 0.29172875 0.         0.98147324]
 [0.73551278 0.47695067 0.61771588 0.84150969 0.2468877 ]]
[[0.14994854 0.20580188 0.23975564 0.26742387 0.07887612]
 [0.32211211 0.15032373 0.29129066 0.11793689 0.06043329]
 [0.15399719 0.33060282 0.15431264 0.08984717 0.25867908]
 [0.03031563 0.04773237 0.10634743 0.01397923 0.32473681]
 [0.24685993 0.16499307 0.20956265 0.28042105 0.0921497 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [29]:
arr = np.random.default_rng().integers(1,20,size=(10))
arr2 = arr.copy()
arr2[arr2.argmax()]=-1
print(arr,arr2,sep='\n')

[ 8 10  3  5  9  2 18  4  2 16]
[ 8 10  3  5  9  2 -1  4  2 16]
